GET http://localhost:3000
  foo: bar
  fizz: buzz

###

POST http://localhost:3000 HTTP/1.1
  
This is the body we are sending
Goodluck!

###
GET http://localhost:3000/ping/
  foo: bar

###
POST http://localhost:3000/ping/
  
Sample test

###
GET https://localhost:3001/ping/
  foo: bar

###
POST https://localhost:3001/ping/
  
Sample test
